### ISSUE TITLE
Validator widget mixin error

### ISSUE THREAD

**Issue by zergionn** [dotmailer/dotmailer-magento2-extension-sms#4]
**Steps to reproduce:**

1. Create a mixin for 'mage/validation' & override/extend ‘listenFormValidateHandler’ method, for instance. here is the documentation - https://devdocs.magento.com/guides/v2.4/javascript-dev-guide/javascript/js_mixins.html#format
2. Deploy static contents & reload the home page

**Expected result:**
There is no JS issue in the console

**Actual result:**
JS error appears in the console "Uncaught TypeError: base is not a constructor at Function.$.widget"

The problem is in this file `telephoneValidatorAddress.js`. The mixin does not return an instance for the mixed widget

**Comment by zergionn** [comment]
PR: #3

**Comment by sta1r** [comment]
@zergionn Again, thanks for flagging this. With this one I can't actually get it to happen locally (with Luma theme at any rate). I have SMS module enabled, and a separate module with a mixin for the `listenFormValidateHandler` method in `mage/validation`. This mixin looks like this:

```
define([], function () {
    'use strict';
    
    return function () {
        console.log('I am extended listenFormValidateHandler');
    };
});
```

On the home page I see the log line and no errors. 

This is really for my understanding. I appreciate you folks are seeing some conflicts with your other extensions, and we're going to get these issues resolved soonest.

**Comment by sta1r** [comment]
Replicated with this code:
```
define([
    'jquery'
], function ($) {
    'use strict';
    return function (widget) {
        $.widget('mage.validation', widget, {
            listenFormValidateHandler: function (event, validation) {
                console.log('I am extended listenFormValidateHandler');
                this._super(event, validation);
            }
        })
        return $.mage.validation;
    };
});
```
