### ISSUE TITLE
It is possible that the account_controller will not be present in the customer_register_success event

### ISSUE THREAD

**Issue by nans** [dotmailer/dotmailer-magento2-extension-sms#8]
**Where**
```
    <event name="customer_register_success">
        <observer name="ddg_customer_register_success_sms" instance="Dotdigitalgroup\Sms\Observer\Customer\Register"/>
    </event>
```

Class: Dotdigitalgroup\Sms\Observer\Customer\Register
```
    public function execute(Observer $observer): void
    {
        $request = $observer->getAccountController()->getRequest()->getPost();
        $customer = $observer->getEvent()->getCustomer();
        $storeId = $customer->getStoreId();
```

**Issue**
It is possible that the account_controller will not be present in the event. I recommend adding handling for such a situation, otherwise, the checkout or any other customized logic may break. For example, Amasty Single Step Checkout 3.1.3 dispatching event without account_controller variable.

**Comment by sta1r** [comment]
Thanks @nans. So, Amasty Single Step Checkout dispatches the `customer_register_success` event at checkout?

**Comment by nans** [comment]
Hi @sta1r, yes (relevant for version 3.1. I can’t say anything about more recent versions).
I see in the Magento code there is a check for the presence of a controller:
![image](https://github.com/dotmailer/dotmailer-magento2-extension-sms/assets/29065937/80d61c7b-588d-451e-881a-87cfd4d40ad7)

**Comment by sta1r** [comment]
Resolved in https://github.com/dotmailer/dotmailer-magento2-extension-sms/releases/tag/v2.0.1. Thanks again @nans!
